# Generated by Django 5.2.1 on 2025-06-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_deleted_at_alter_books_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Returned'), (3, 'Reserved'), (4, 'Assigned'), (5, 'Deleted'), (6, 'Overdue')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentbooks',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Returned'), (3, 'Reserved'), (4, 'Assigned'), (5, 'Deleted'), (6, 'Overdue')], default=4),
        ),
    ]
